name=LGFX_Fonts
version=1.1.2
author=tobozo
maintainer=tobozo
sentence=External fonts support for LovyanGFX/M5GFX
paragraph=Support external fonts from outside LGFX
category=Display
url=https://github.com/tobozo/LGFX_Fonts
includes=LGFX_Fonts.hpp
architectures=esp32,esp8266,samd,rp2040,mbed_rp2040,mbed_nano
