/*\
 *
  LGFX_Fonts - External fonts support for LovyanGFX/M5GFX

  Original Source:
  https://github.com/tobozo/LGFX_Fonts

  Licence:
  [Multiple](https://github.com/tobozo/LGFX_Fonts/blob/master/LICENSE.txt)

  Author:
  [tobozo](https://github.com/tobozo)

  Contributors:
  [ciniml](https://github.com/ciniml)
  [mongonta0716](https://github.com/mongonta0716)
  [lovyan03](https://twitter.com/lovyan03)

\*/
/* code generated by export_emoji_to_C.php */

#include "8x8/emojis_packed_8x8.h"
#include "16x16/emojis_packed_16x16.h"
#include "24x24/emojis_packed_24x24.h"
#include "32x32/emojis_packed_32x32.h"
#include "64x64/emojis_packed_64x64.h"
