; Inspired from https://github.com/Jason2866/Tasmota-build
[platformio]
description = LGFX_Font emoji example
src_dir = main

[coding_standards]
build_flags       =
    -Wno-unused-variable
    -Wno-unused-but-set-variable
    -Wno-sign-compare
    -Wunreachable-code
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -Wformat
    -Wnonnull

[env]
framework = arduino
lib_deps = LGFX_Font

[platform_default]
platformio        = platform-espressif32
pioarduino        = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[espressif32_latest]
platform          = ${platform_default.pioarduino}
build_flags       = ${coding_standards.build_flags}

[M5Stack]
board             = m5stack-core-esp32


[env:m5stack-m5gfx]
extends          = M5Stack, espressif32_latest
lib_deps =
  ${env.lib_deps}
  M5GFX
  M5Unified
build_flags =
  ${env.build_flags}
  -DCONFIG_LGFX_FONT_USE_M5GFX


[env:m5stack-lgfx]
extends          = M5Stack, espressif32_latest
lib_deps =
  ${env.lib_deps}
  LovyanGFX
build_flags =
  ${env.build_flags}
  -DCONFIG_LGFX_FONT_USE_LGFX

