<?php

/*\
 *
 *

  Copyright 2026 tobozo

  https://github.com/tobozo

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the “Software”), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
  of the Software, and to permit persons to whom the Software is furnished to do
  so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.

 *
 *
\*/

/*
 *

 /!\ This php script is intended to be called from create_emojis.sh

 Jobs:
  - Generate C code from png images (arrays of bytes)
  - Generate headers for emojis/groups/subgroups collections
  - Generate documentation

*/

if(!isset($argv[1]) || !preg_match("/^[0-9]+$/", $argv[1]))
  die(sprintf("Usage: php %s [png size]".PHP_EOL, basename(__FILE__)));

$pngSize = $argv[1];
$packSuffix = sprintf("%dx%d", $pngSize, $pngSize);

$pngDir = sprintf("png%s", $packSuffix); // folder containing all fonts generated with extract_emoji.py i.e. format("u%x.png", unicode)

if(!is_dir($pngDir) || empty($pngFiles=glob("$pngDir/*.png")))
{
  die("\nError: png dir '$pngDir' not found\nPlease run 'python3 extract_emoji.py /path/to/NotoColorEmoji.ttf --resize $pngSize --output png$packSuffix'".PHP_EOL.PHP_EOL);
}

$c_includes_file = "emojis.h";
$c_struct_file   = "emojis_structs.h";
$c_data_file     = sprintf("%s/emojis_data_%s.h", $packSuffix, $packSuffix);
$c_pack_file     = sprintf("%s/emojis_packed_%s.h", $packSuffix, $packSuffix);
$readme_file     = "ReadMe.emojis.md";

if(!is_dir($packSuffix))
  mkdir($packSuffix) or die("Unable to create output dir $packSuffix".PHP_EOL);

$license = "
/*\
 *
  LGFX_Fonts - External fonts support for LovyanGFX/M5GFX

  Original Source:
  https://github.com/tobozo/LGFX_Fonts

  Licence:
  [Multiple](https://github.com/tobozo/LGFX_Fonts/blob/master/LICENSE.txt)

  Author:
  [tobozo](https://github.com/tobozo)

  Contributors:
  [ciniml](https://github.com/ciniml)
  [mongonta0716](https://github.com/mongonta0716)
  [lovyan03](https://twitter.com/lovyan03)

\*/
";

$header_comment = trim($license).PHP_EOL.sprintf("/* code generated by %s */".PHP_EOL, basename(__FILE__));

$extern_c_open  = '#ifdef __cplusplus'.PHP_EOL.'extern "C" {'.PHP_EOL.'#endif'.PHP_EOL;
$extern_c_close = '#ifdef __cplusplus'.PHP_EOL.'}'.PHP_EOL.'#endif'.PHP_EOL;

// create empty files
file_put_contents($c_struct_file, $header_comment)!==false or die("Unable to create $c_struct_file");
file_put_contents($c_data_file,   $header_comment)!==false or die("Unable to create $c_data_file");
file_put_contents($c_pack_file,   $header_comment)!==false or die("Unable to create $c_pack_file");




$total = 0;
$ignored = 0;
$notfound = 0;
$use_defines = false;
$raw_emojis_list = false;

$emoji_groups = [];


// Download emojis meta information (e.g. code, group+subgroup and emoji names)
{
  if(!file_exists("all_emojis.json"))
  {
    $emojis_json_txt = file_get_contents("https://unpkg.com/emoji.json/emoji.json") or die("Unable to fetch https://unpkg.com/emoji.json/emoji.json");
    file_put_contents("all_emojis.json", $emojis_json_txt) or die("Unable to save all_emojis.json");
  } else{
    $emojis_json_txt = file_get_contents("all_emojis.json");
  }
  $emojis_json = json_decode($emojis_json_txt, true);

  if(empty($emojis_json))
    die("Invalid data in all_emojis.json, delete the file and try again");
}

echo sprintf("Initial Count: %d".PHP_EOL, count($emojis_json));


// Hydrate array with png data
{
  foreach($emojis_json as $num => $emoji)
  {
    if(!preg_match("/^[a-f0-9]{4,6}$/i", $emoji['codes']))
    { // emojis with code larger than 24bits (e.g. combined) aren't supported by LovyanGFX
      unset($emojis_json[$num]);
      continue;
    }

    $subgroupname = string_to_c_var($emoji['subgroup']);
    $groupname = string_to_c_var($emoji['group']);

    if(!isset($emoji_groups[$groupname]))
      $emoji_groups[$groupname] = [];

    if(!isset($emoji_groups[$groupname][$subgroupname]))
      $emoji_groups[$groupname][$subgroupname] = [];

    $fname = sprintf("$pngDir/u%s.png", strtoupper($emoji['codes']));
    if(!file_exists($fname))
    { // emoji is documented in json file but wasn't extracted by extract_emoji.py ?
      echo sprintf("%s [$groupname] %s, 0x%s (%s) not found".PHP_EOL, $emoji['char'], $fname, $emoji['codes'], $emoji['name']);
      $notfound++;
      continue;
    }

    list($emoji['width'], $emoji['height'], $type, $attr) = getimagesize($fname);
    $xxdname = preg_replace("/[^a-z0-9]+/i", "_", basename($fname)).sprintf("_%dx%d", $emoji['width'], $emoji['height']);
    $emoji['c'] = sprintf("{ 0x%-5s, \"%s\", GROUP_%s, SUBGROUP_%s, %s, %s_len}, // %s", $emoji['codes'], $emoji['char'], $groupname, $subgroupname, $xxdname, $xxdname, $emoji['name']);
    $emoji['xxd'] = xxd($fname, $xxdname);
    $emoji['filename'] = basename($fname);
    $emoji['bytes'] = filesize($fname);
    $emoji_groups[$groupname][$subgroupname][] = $emoji;
    $total++;
  }
}


echo sprintf("Filtered Count: %d".PHP_EOL, count($emojis_json));


$header_readme = sprintf("
### LGFX_Emojis

There are **%d** unique emojis in this package.
Each one is available in 8x8, 16x16, 24x24, 32x32 and 64x64, totalling **%d** png images.

## How will all this fit on flash?

The Unicode Consortium has organized all emojis in categories, groups and subgroups.

- **group**
  - group, e.g. *Smileys & Emotion*
- **subgroup**
  - sub group sub group, e.g. *face-smiling*

LGFX_Font provides the relevant declarations for each of those groups/subgroups to allow the creation of custom sets.
**Only the emojis actually selected at compile time are included in the firmware.**

Custom sets can be composed by creating one array of the following C types:

- `emoji_png_t { uint32_t code, ... }` **emoji_data**: an Emoji
- `emoji_png_set_t { emoji_png_t* emojis, size_t count }` **subgroup**: a collection of Emojis
- `emoji_png_group_t { emoji_png_set_t* subgroups, size_t count}` **group**: a collection of **subgroups**

See [`src/Fonts/emojis/emojis_structs.h`](src/Fonts/emojis/emojis_structs.h) for more details.

For convenience, the following complete sets are available:

- `all_groups_8x8`
- `all_groups_16x16`
- `all_groups_24x24`
- `all_groups_32x32`
- `all_groups_64x64`

Some of those will only compile with big partitions though.

Loading all 24x24 emojis consumes a lot of program storage space:
```cpp
  lgfx::LGFX_Emojis::loadEmojis(&lcd, all_groups_24x24);
```

Loading all 16x16 emojis from a smaller set may save some of it:
```cpp
  lgfx::LGFX_Emojis::loadEmojis(&lcd, all_groups_16x16);
```

Loading all 8x8 emojis from an even smaller set will produce pixelated emojis:
```cpp
  lgfx::LGFX_Emojis::loadEmojis(&lcd, all_groups_8x8);
```

Mixing different sizes is okay, just create a custom set from subgroups:
```cpp
  const emoji_png_set_t emoji_subgroups[] = {subgroup_FACE_SMILING_32x32, subgroup_FACE_TONGUE_8x8, subgroup_HAND_FINGERS_OPEN_24x24, subgroup_TRANSPORT_SIGN_64x64};
  lgfx::LGFX_Emojis::loadEmojis(&lcd, emoji_subgroups);
```

Or create bigger custom sets from groups:
```cpp
  const emoji_png_group_t emoji_groups[] = { group_SMILEYS_EMOTION_64x64, group_PEOPLE_BODY_64x64 };
  lgfx::LGFX_Emojis::loadEmojis(&lcd, emoji_groups);
```

All groups/subgroups names are derived from [emojis.json](https://unpkg.com/emoji.json@16.0.0/emoji.json) package and are listed below.

", count($emojis_json), count($emojis_json)*5);

if($pngSize==8)
  file_put_contents($readme_file, $header_readme)!==false or die("Unable to create $c_pack_file");


// Add png bytes to data file
{
  $guard_name = preg_replace("/[^a-z0-9]+/i", "_", strtoupper(basename($c_data_file)));
  $include_guard = sprintf('#if !defined %s'.PHP_EOL.'#define %s'.PHP_EOL, $guard_name, $guard_name );
  file_put_contents("$c_data_file", PHP_EOL.$include_guard.PHP_EOL.$extern_c_open.PHP_EOL, FILE_APPEND);

  foreach($emoji_groups as $groupname => $subgroup)
  {
    foreach($subgroup as $subgroupname => $emojis )
    {
      foreach($emojis as $emoji)
      {
        $fileInfo = sprintf("// file: %s, width: %dpx, height: %dpx, size: %d bytes".PHP_EOL, $emoji['filename'], $emoji['width'], $emoji['height'], $emoji['bytes']);
        file_put_contents("$c_data_file", $fileInfo, FILE_APPEND);
        file_put_contents("$c_data_file", $emoji['xxd'], FILE_APPEND);
      }
    }
  }
  file_put_contents("$c_data_file", PHP_EOL.$extern_c_close.PHP_EOL, FILE_APPEND);
  file_put_contents("$c_data_file", PHP_EOL.'#endif // defined '.$guard_name.PHP_EOL, FILE_APPEND);
}



// Add define flags to header file
{

  $guard_name = preg_replace("/[^a-z0-9]+/i", "_", strtoupper(basename($c_pack_file)));
  $include_guard = sprintf('#if !defined %s'.PHP_EOL.'#define %s'.PHP_EOL, $guard_name, $guard_name );
  file_put_contents("$c_pack_file", PHP_EOL.$include_guard.PHP_EOL.$extern_c_open.PHP_EOL, FILE_APPEND);

  $header = sprintf('#include "%s"'.PHP_EOL.'#include "../%s"'.PHP_EOL, basename($c_data_file), $c_struct_file);
  file_put_contents("$c_pack_file", $header, FILE_APPEND);

  foreach($emoji_groups as $groupname => $subgroup)
  {
    $groupcount = 0;
    $groupbytes =  0;

    $subgroupDefine = sprintf('#if defined USE_GROUP_%s'.PHP_EOL, $groupname);

    foreach($subgroup as $subgroupname => $emojis )
    {
      if(count($emojis)==0)
      { // group is empty i.e. none of its emojis are supported by LovyanGFX
        unset($emoji_groups[$groupname]);
        continue;
      }

      $subgroupbytes = 0;
      $subgroupcount = count($emojis);
      $groupcount += $subgroupcount;

      foreach($emojis as $emoji)
      {
        $subgroupbytes += $emoji['bytes'];
        $groupbytes    += $emoji['bytes'];
      }

      $subgroupDefine .= sprintf("  #define USE_SUBGROUP_%s // %d items (%d bytes)".PHP_EOL, $subgroupname, $subgroupcount, $subgroupbytes);
    }

    $subgroupDefine .= '#endif'.PHP_EOL;

    $groupDefine = sprintf("#define USE_GROUP_%s // %d items (%d bytes)".PHP_EOL, $groupname, $groupcount, $groupbytes);

    if( $raw_emojis_list && $use_defines )
      file_put_contents("$c_pack_file", $groupDefine.$subgroupDefine.PHP_EOL, FILE_APPEND);
  }
}


// Add emoji data struct and enums to header file
{
  $header = "

#if !defined EMOJIS_STRUCTS_H
#define EMOJIS_STRUCTS_H

$extern_c_open

// data struct for one emoji
struct emoji_png_t {
  uint32_t code;
  const char* emoji;
  int group_id;
  int subgroup_id;
  const uint8_t* data;
  unsigned int data_len;
};


// subgroup : a collection of emojis
struct emoji_png_set_t {
  const emoji_png_t* emojis;
  size_t count;
};


// group : a collection of subgroups
struct emoji_png_group_t {
  const emoji_png_set_t* subgroups;
  size_t count;
};


";

  file_put_contents("$c_struct_file", $header, FILE_APPEND);


  // Add emoji groups enumeration to header file
  {
    $groupenums = "enum emoji_group_id_t {".PHP_EOL;
    $subgroupenums = "enum emoji_subgroup_id_t {".PHP_EOL;

    foreach($emoji_groups as $groupname => $subgroup)
    {
      $groupenums .= sprintf("  GROUP_%s,".PHP_EOL, $groupname);
      foreach($subgroup as $subgroupname => $emojis )
      {
        $subgroupenums .= sprintf("  SUBGROUP_%s,".PHP_EOL, $subgroupname);
      }
    }

    $groupenums .= "};".PHP_EOL.PHP_EOL;
    $subgroupenums .= "};".PHP_EOL.PHP_EOL;

    file_put_contents("$c_struct_file", $groupenums.$subgroupenums, FILE_APPEND);
  }

  file_put_contents("$c_struct_file", PHP_EOL.$extern_c_close.PHP_EOL, FILE_APPEND);
  file_put_contents("$c_struct_file", PHP_EOL.'#endif // defined EMOJIS_STRUCTS_H'.PHP_EOL, FILE_APPEND);

}




// Add RAW emoji list to header file
if( $raw_emojis_list )
{
  file_put_contents("$c_pack_file", sprintf('static const emoji_png_t all_emojis_%s[] = {'.PHP_EOL, $packSuffix), FILE_APPEND);

  foreach($emoji_groups as $groupname => $subgroup)
  {
    $emojis_code = '';
    if( $use_defines ) $emojis_code = sprintf(PHP_EOL."#if defined USE_GROUP_%s".PHP_EOL, $groupname );

    foreach($subgroup as $subgroupname => $emojis )
    {
      if( $use_defines ) $emojis_code .= sprintf(PHP_EOL."  #if defined USE_SUBGROUP_%s".PHP_EOL, $subgroupname );
      foreach($emojis as $emoji)
      {
        $emojis_code .= '    '.$emoji['c'].PHP_EOL;
      }
      if( $use_defines ) $emojis_code .= sprintf("  #endif // defined USE_SUBGROUP_%s".PHP_EOL, $subgroupname);
    }

    if( $use_defines ) $emojis_code .= sprintf(PHP_EOL."#endif // defined USE_GROUP_%s".PHP_EOL, $groupname);
    file_put_contents("$c_pack_file", $emojis_code, FILE_APPEND);
  }

  file_put_contents("$c_pack_file", '};'.PHP_EOL, FILE_APPEND);
}


// Add SUBGROUP and GROUP emoji data to header file
{
  $allgroups = sprintf("static const emoji_png_group_t all_groups_%s[] = {".PHP_EOL, $packSuffix);

  file_put_contents("$readme_file", PHP_EOL."## Size `$packSuffix`".PHP_EOL.PHP_EOL, FILE_APPEND);

  // file_put_contents("$readme_file", sprintf("| %-29s | %-39s |".PHP_EOL,"Group Name", "Subgroup Name"), FILE_APPEND);
  // file_put_contents("$readme_file", "| ----------------------------- | --------------------------------------- |".PHP_EOL, FILE_APPEND);
  // file_put_contents("$readme_file",
  //   sprintf("| %-29s | %-39s |".PHP_EOL,
  //       '**Type**: '.backtick_string("emoji_png_group_t"),
  //       '**Type**: '.backtick_string("emoji_png_set_t")),
  //   FILE_APPEND
  // );
  // file_put_contents("$readme_file", sprintf("| %-29s | %-39s |".PHP_EOL.PHP_EOL,"<img width=300/>", "<img width=300/>"), FILE_APPEND);

  // | First Header  | Second Header |
  // | ------------- | ------------- |
  // | Content Cell  | Content Cell  |
  // | Content Cell  | Content Cell  |


  foreach($emoji_groups as $groupname => $subgroup)
  {
    $groupset_name = sprintf("group_set_%s_%s", $groupname, $packSuffix);
    $group_name = sprintf("group_%s_%s", $groupname, $packSuffix);
    $subgroups = sprintf(PHP_EOL."const emoji_png_set_t %s[] = {".PHP_EOL, $groupset_name);

    $subgroups_count = count($subgroup);
    $subgroups_count_txt = $subgroups_count.' '.($subgroups_count>1 ? "subgroups" : "subgroup");

    file_put_contents("$readme_file", sprintf("<details><summary><code>%s</code> (%s)</summary>".PHP_EOL.PHP_EOL, $group_name, $subgroups_count_txt), FILE_APPEND);


    foreach($subgroup as $subgroupname => $emojis )
    {
      $emojiset_name = sprintf('emojis_set_%s_%s', $subgroupname, $packSuffix);
      $subgroup_name = sprintf('subgroup_%s_%s', $subgroupname, $packSuffix);
      $emojis_code = "";
      file_put_contents("$c_pack_file", PHP_EOL.'static const emoji_png_t '.$emojiset_name.'[] = {'.PHP_EOL, FILE_APPEND);
      foreach($emojis as $emoji)
      {
        $emojis_code .= '    '.$emoji['c'].PHP_EOL;
      }
      file_put_contents("$c_pack_file", $emojis_code, FILE_APPEND);
      file_put_contents("$c_pack_file", '};'.PHP_EOL, FILE_APPEND);
      $emojis_set = sprintf("static const emoji_png_set_t %s = {%s, sizeof(%s)/sizeof(emoji_png_t) };".PHP_EOL.PHP_EOL,
        $subgroup_name, $emojiset_name, $emojiset_name
      );
      file_put_contents("$c_pack_file", $emojis_set, FILE_APPEND);
      //file_put_contents("$readme_file", sprintf("| %-29s | %-39s |".PHP_EOL,"", backtick_string($subgroup_name) ), FILE_APPEND);
      file_put_contents("$readme_file", sprintf("- %s".PHP_EOL, backtick_string($subgroup_name) ), FILE_APPEND);
      $subgroups .= "    $subgroup_name,".PHP_EOL;
    }
    $subgroups .= "};".PHP_EOL;
    $subgroups .= sprintf("static const emoji_png_group_t %s = { %s, sizeof(%s)/sizeof(emoji_png_set_t) };".PHP_EOL.PHP_EOL, $group_name, $groupset_name, $groupset_name);
    file_put_contents("$c_pack_file", $subgroups, FILE_APPEND);

    //file_put_contents("$readme_file", sprintf("| %-29s | %-39s |".PHP_EOL,"<img width=300/>", "<img width=300/>"), FILE_APPEND);
    file_put_contents("$readme_file", PHP_EOL.'</details>'.PHP_EOL, FILE_APPEND);

    $allgroups .= sprintf("    %s,".PHP_EOL, $group_name);
  }

  $allgroups .= "};".PHP_EOL.PHP_EOL;

  file_put_contents("$c_pack_file", $allgroups, FILE_APPEND);
}


file_put_contents("$c_pack_file", PHP_EOL.$extern_c_close.PHP_EOL, FILE_APPEND);
file_put_contents("$c_pack_file", PHP_EOL.'#endif // defined '.$guard_name.PHP_EOL, FILE_APPEND);


// append include to global file
{
  if(!file_exists( $c_includes_file ))
  {
    file_put_contents($c_includes_file, $header_comment.PHP_EOL)!==false or die("Unable to create $c_includes_file");
  }
  $includes_file_contents = file_get_contents($c_includes_file) or die("Unable to re-read $c_includes_file");
  $include_string = sprintf('#include "%s"', $c_pack_file);
  if(substr_count($includes_file_contents, $include_string)<=0)
  {
    file_put_contents("$c_includes_file", $include_string.PHP_EOL, FILE_APPEND);
  }

}

echo sprintf("Total: %d, Ignored: %d, Not Found: %d".PHP_EOL, $total, $ignored, $notfound);


exit;



function backtick_string($string)
{
  return sprintf('`%s`', $string);
}

function string_to_c_var($string)
{
  $string = preg_replace("/[^a-z0-9]+/i", "_", strtoupper($string));
  $string = preg_replace("/_+/", "_", $string);
  return $string;
}


function xxd($filename, $cname="", $cols=16)
{
  if(!file_exists($filename))
    return '';

  if($cols<8)
    $cols = 8;

  if($cname=='')
    $cname=basename($filename);

  $hex_array = unpack("C*",file_get_contents($filename));

  $chunked_array = array_chunk($hex_array, $cols);

  $ret = sprintf("static const unsigned char %s[] = {".PHP_EOL, $cname);

  foreach($chunked_array as $array_col)
  {
    $line = "  ";
    foreach($array_col as $hexcol)
    {
      $line .= sprintf("0x%02x, ", $hexcol);
    }
    $ret .= $line.PHP_EOL;
  }

  $ret .= "};".PHP_EOL.PHP_EOL;
  $ret .= sprintf("static const unsigned int %s_len = %d;".PHP_EOL.PHP_EOL, $cname, count($hex_array));

  return $ret;
}

